import type { FormatFnArguments } from 'style-dictionary/types'
import prettier from 'prettier'

const GENERATED_FILE_HEADER = [
  '/*',
  ' * This file is generated by Style Dictionary.',
  ' * Do not edit this file manually.',
  ' */',
  '',
].join('\n')

const THEME_NAMES = ['light', 'dark'] as const
const TYPESCRIPT_PRETTIER_OPTIONS = {
  parser: 'typescript',
  semi: false,
  singleQuote: true,
  trailingComma: 'all',
} as const
const MONACO_RULES = [
  { token: '', key: 'default' },
  { token: 'comment', key: 'comment' },
  { token: 'keyword', key: 'keyword' },
  { token: 'string', key: 'string' },
  { token: 'number', key: 'number' },
  { token: 'type', key: 'type' },
  { token: 'delimiter', key: 'delimiter' },
  { token: 'operator', key: 'operator' },
  { token: 'identifier', key: 'identifier' },
] as const

function formatCssVariables({ dictionary }: FormatFnArguments) {
  const lines = [GENERATED_FILE_HEADER]

  for (const theme of THEME_NAMES) {
    lines.push(`[data-workspace-theme='${theme}'] {`)

    getThemeEditorColorTokens(dictionary.allTokens, theme).forEach((token) => {
      lines.push(
        `  --editor-color-${toKebabCase(token.path.slice(5).join('-'))}: ${String(token.value)};`,
      )
    })

    lines.push('}', '')
  }

  return lines.join('\n')
}

async function formatTypeScriptTokens({ dictionary }: FormatFnArguments) {
  const colorTokens = Object.fromEntries(
    THEME_NAMES.map((theme) => [
      theme,
      Object.fromEntries(
        getThemeEditorColorTokens(dictionary.allTokens, theme).map((token) => [
          token.path.slice(5).join('.'),
          String(token.value),
        ]),
      ),
    ]),
  )

  return prettier.format(
    [
      GENERATED_FILE_HEADER,
      'export const EDITOR_THEME_COLOR_TOKENS = ',
      `${JSON.stringify(colorTokens, null, 2)} as const`,
      '',
      'export const EDITOR_COLOR_VARIABLES = {',
      "  diagramGridDot: 'var(--editor-color-diagram-grid-dot)',",
      "  relationLine: 'var(--editor-color-relation-line, currentColor)',",
      "  relationSource: 'var(--editor-color-relation-source)',",
      "  relationReference: 'var(--editor-color-relation-reference)',",
      '} as const',
      '',
    ].join('\n'),
    TYPESCRIPT_PRETTIER_OPTIONS,
  )
}

async function formatMonacoThemes({ dictionary }: FormatFnArguments) {
  const themes = Object.fromEntries(
    THEME_NAMES.map((theme) => [
      theme,
      getMonacoTheme(dictionary.allTokens, theme),
    ]),
  )

  return prettier.format(
    [
      GENERATED_FILE_HEADER,
      "import type { editor } from 'monaco-editor'",
      '',
      'export const EDITOR_MONACO_THEME_DEFINITIONS = ',
      `${JSON.stringify(themes, null, 2)} satisfies Record<'light' | 'dark', editor.IStandaloneThemeData>`,
      '',
    ].join('\n'),
    TYPESCRIPT_PRETTIER_OPTIONS,
  )
}

function getThemeEditorColorTokens(
  tokens: FormatFnArguments['dictionary']['allTokens'],
  theme: (typeof THEME_NAMES)[number],
) {
  return tokens.filter(
    (token) =>
      token.path[0] === 'component' &&
      token.path[1] === 'theme' &&
      token.path[2] === theme &&
      token.path[3] === 'editor' &&
      token.path[4] === 'color',
  )
}

function getMonacoTheme(
  tokens: FormatFnArguments['dictionary']['allTokens'],
  theme: (typeof THEME_NAMES)[number],
) {
  return {
    base: getTokenValue(tokens, [
      'component',
      'theme',
      theme,
      'monaco',
      'base',
    ]),
    inherit: true,
    rules: MONACO_RULES.map(({ token, key }) => {
      const rule = {
        token,
        foreground: stripHash(
          getTokenValue(tokens, [
            'component',
            'theme',
            theme,
            'monaco',
            'rule',
            key,
            'foreground',
          ]),
        ),
      }
      const fontStyle = getOptionalTokenValue(tokens, [
        'component',
        'theme',
        theme,
        'monaco',
        'rule',
        key,
        'fontStyle',
      ])

      return fontStyle ? { ...rule, fontStyle } : rule
    }),
    colors: {
      'editor.background': getTokenValue(tokens, [
        'component',
        'theme',
        theme,
        'monaco',
        'background',
      ]),
      'editor.foreground': getTokenValue(tokens, [
        'component',
        'theme',
        theme,
        'monaco',
        'foreground',
      ]),
      'editorLineNumber.foreground': getTokenValue(tokens, [
        'component',
        'theme',
        theme,
        'monaco',
        'lineNumber',
      ]),
      'editorLineNumber.activeForeground': getTokenValue(tokens, [
        'component',
        'theme',
        theme,
        'monaco',
        'lineNumberActive',
      ]),
      'editorCursor.foreground': getTokenValue(tokens, [
        'component',
        'theme',
        theme,
        'monaco',
        'cursor',
      ]),
      'editor.selectionBackground': getTokenValue(tokens, [
        'component',
        'theme',
        theme,
        'monaco',
        'selection',
      ]),
      'editor.inactiveSelectionBackground': getTokenValue(tokens, [
        'component',
        'theme',
        theme,
        'monaco',
        'inactiveSelection',
      ]),
      'editor.lineHighlightBackground': getTokenValue(tokens, [
        'component',
        'theme',
        theme,
        'monaco',
        'lineHighlight',
      ]),
      'editorWhitespace.foreground': getTokenValue(tokens, [
        'component',
        'theme',
        theme,
        'monaco',
        'whitespace',
      ]),
      'editorIndentGuide.background1': getTokenValue(tokens, [
        'component',
        'theme',
        theme,
        'monaco',
        'indentGuide',
      ]),
      'editorIndentGuide.activeBackground1': getTokenValue(tokens, [
        'component',
        'theme',
        theme,
        'monaco',
        'indentGuideActive',
      ]),
    },
  }
}

function getTokenValue(
  tokens: FormatFnArguments['dictionary']['allTokens'],
  path: string[],
) {
  const value = getOptionalTokenValue(tokens, path)

  if (!value) {
    throw new Error(`Missing design token: ${path.join('.')}`)
  }

  return value
}

function getOptionalTokenValue(
  tokens: FormatFnArguments['dictionary']['allTokens'],
  path: string[],
) {
  return tokens.find((token) => pathsMatch(token.path, path))?.value as
    | string
    | undefined
}

function pathsMatch(left: string[], right: string[]) {
  return (
    left.length === right.length &&
    left.every((part, index) => part === right[index])
  )
}

function stripHash(value: string) {
  return value.startsWith('#') ? value.slice(1) : value
}

function toKebabCase(value: string) {
  return value.replaceAll(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
}

export default {
  log: {
    warnings: 'disabled',
  },
  hooks: {
    formats: {
      'dbml-drawer/css-variables': formatCssVariables,
      'dbml-drawer/tokens-ts': formatTypeScriptTokens,
      'dbml-drawer/monaco-themes-ts': formatMonacoThemes,
    },
  },
  source: ['design-tokens/**/*.json'],
  platforms: {
    css: {
      buildPath: 'src/shared/design-tokens/generated/',
      files: [
        {
          destination: 'tokens.css',
          format: 'dbml-drawer/css-variables',
        },
      ],
    },
    ts: {
      buildPath: 'src/shared/design-tokens/generated/',
      files: [
        {
          destination: 'tokens.ts',
          format: 'dbml-drawer/tokens-ts',
        },
        {
          destination: 'monaco-themes.ts',
          format: 'dbml-drawer/monaco-themes-ts',
        },
      ],
    },
  },
}
